#ifndef GUARD_CONSTANTS_ABILITIES_H
#define GUARD_CONSTANTS_ABILITIES_H

 enum __attribute__((packed)) Ability
{
 ABILITY_NONE = 0,
 ABILITY_STENCH = 1,
 ABILITY_DRIZZLE = 2,
 ABILITY_SPEED_BOOST = 3,
 ABILITY_BATTLE_ARMOR = 4,
 ABILITY_STURDY = 5,
 ABILITY_DAMP = 6,      //reduce fire damage, also blocks aftermath
 ABILITY_LIMBER = 7,
 ABILITY_SAND_VEIL = 8,
 ABILITY_STATIC = 9,
 ABILITY_VOLT_ABSORB = 10,
 ABILITY_WATER_ABSORB = 11,
 ABILITY_OBLIVIOUS = 12,
 ABILITY_CLOUD_NINE = 13,
 ABILITY_COMPOUND_EYES = 14,
 ABILITY_INSOMNIA = 15,
 ABILITY_COLOR_CHANGE = 16,
 ABILITY_IMMUNITY = 17,
 ABILITY_FLASH_FIRE = 18,
 ABILITY_SHIELD_DUST = 19,
 ABILITY_OWN_TEMPO = 20,
 ABILITY_SUCTION_CUPS = 21,
 ABILITY_INTIMIDATE = 22,
 ABILITY_SHADOW_TAG = 23,
 ABILITY_ROUGH_SKIN = 24,
 ABILITY_WONDER_GUARD = 25,
 ABILITY_FEMME_FATALE = 26, //since removing can replace with something else idk what though possibly anercomps random high roller ability or perhaps a community poll
 ABILITY_EFFECT_SPORE = 27,  //ABILITY_FEMME_FATALE  replacement for levitate  //think will also give to jinx as well
 ABILITY_SYNCHRONIZE = 28,
 ABILITY_CLEAR_BODY = 29,
 ABILITY_NATURAL_CURE = 30,
 ABILITY_LIGHTNING_ROD = 31,
 ABILITY_SERENE_GRACE = 32,
 ABILITY_SWIFT_SWIM = 33,
 ABILITY_CHLOROPHYLL = 34,
 ABILITY_ILLUMINATE = 35,
 ABILITY_TRACE = 36,
 ABILITY_HUGE_POWER = 37, //given mostly bunny mon as japanese "pun" related to bunnies or moon goddess
 ABILITY_POISON_POINT = 38,
 ABILITY_INNER_FOCUS = 39,
 ABILITY_MAGMA_ARMOR = 40,
 ABILITY_WATER_VEIL = 41,
 ABILITY_MAGNET_PULL = 42,
 ABILITY_SOUNDPROOF = 43,
 ABILITY_RAIN_DISH = 44,
 ABILITY_SAND_STREAM = 45,
 ABILITY_PRESSURE = 46,
 ABILITY_THICK_FAT = 47,
 ABILITY_EARLY_BIRD = 48,
 ABILITY_FLAME_BODY = 49,
 ABILITY_RUN_AWAY = 50,
 ABILITY_KEEN_EYE = 51,
 ABILITY_HYPER_CUTTER = 52,
 ABILITY_PICKUP = 53,
 ABILITY_TRUANT = 54,
 ABILITY_HUSTLE = 55,
 ABILITY_CUTE_CHARM = 56,
 ABILITY_PLUS = 57,
 ABILITY_MINUS = 58,
 ABILITY_FORECAST = 59,
 ABILITY_STICKY_HOLD = 60,
 ABILITY_SHED_SKIN = 61,
 ABILITY_GUTS = 62,
 ABILITY_MARVEL_SCALE = 63,
 ABILITY_LIQUID_OOZE = 64,
 ABILITY_OVERGROW = 65,
 ABILITY_BLAZE = 66,
 ABILITY_TORRENT = 67,
 ABILITY_SWARM = 68,
 ABILITY_ROCK_HEAD = 69,
 ABILITY_DROUGHT = 70,
 ABILITY_ARENA_TRAP = 71,
 ABILITY_VITAL_SPIRIT = 72,
 ABILITY_WHITE_SMOKE = 73,
 ABILITY_PURE_POWER = 74,  //nother pun I believe japanese refers to yoga, and is separate ability since other is for rabbits so give pure power over huge power if decide to use boost
 ABILITY_SHELL_ARMOR = 75,
 ABILITY_CACOPHONY = 76, //used made new effect
 ABILITY_AIR_LOCK = 77,

  ABILITIES_COUNT_GEN3 = 78,
// Gen_4
 ABILITY_TANGLED_FEET = ABILITIES_COUNT_GEN3,
 ABILITY_MOTOR_DRIVE = 79,
 ABILITY_RIVALRY = 80,
 ABILITY_STEADFAST = 81,
 ABILITY_SNOW_CLOAK = 82,
 ABILITY_GLUTTONY = 83,
 ABILITY_ANGER_POINT = 84,
 ABILITY_UNBURDEN = 85,
 ABILITY_HEATPROOF = 86,
 ABILITY_SIMPLE = 87,
 ABILITY_DRY_SKIN = 88,
 ABILITY_DOWNLOAD = 89,
 ABILITY_IRON_FIST = 90,
 ABILITY_POISON_HEAL = 91,
 ABILITY_ADAPTABILITY = 92,
 ABILITY_SKILL_LINK = 93,
 ABILITY_HYDRATION = 94,    //plan buff to include any negative status, so yawn think attraction taunt torment and also destiny bond  perish song? nah too much
 ABILITY_SOLAR_POWER = 95,
 ABILITY_QUICK_FEET = 96,
 ABILITY_NORMALIZE = 97, //gets power boost + stab, but always neutral dmg, have to give to weak mon, is pretty much huge power
 ABILITY_SNIPER = 98,
 ABILITY_MAGIC_GUARD = 99,
 ABILITY_NO_GUARD = 100,
 ABILITY_STALL = 101,	//made specifically and only for sableye, doesnt synergize with trick room potentially worst abilityin the game... vsonic  -fixed
 ABILITY_TECHNICIAN = 102,
 ABILITY_LEAF_GUARD = 103,
 ABILITY_KLUTZ = 104,
 ABILITY_MOLD_BREAKER = 105, //this is actually much better than I thought, hits wonderguard ignores things that affect move dmg or absorb abilities etc.
 ABILITY_SUPER_LUCK = 106,
 ABILITY_AFTERMATH = 107, //do something more with this, maybe give a switch out effect and then strengthen faint effect? = 2,/5 = 2,/6 or like a weaker counter, takes portion of movedmg??
 ABILITY_ANTICIPATION = 108, //oh aftermath already does = 2,/5 enemy max health
 ABILITY_FOREWARN = 109,
 ABILITY_UNAWARE = 110,
 ABILITY_TINTED_LENS = 111,
 ABILITY_FILTER = 112,
 ABILITY_SLOW_START = 113,
 ABILITY_SCRAPPY = 114,
 ABILITY_STORM_DRAIN = 115,
 ABILITY_ICE_BODY = 116,
 ABILITY_SOLID_ROCK = 117,
 ABILITY_SNOW_WARNING = 118,
 ABILITY_HONEY_GATHER = 119, //add woot change idea that holding honey will act like leftovers
 ABILITY_FRISK = 120,
 ABILITY_RECKLESS = 121,
 ABILITY_MULTITYPE = 122,
 ABILITY_FLOWER_GIFT = 123,
 ABILITY_BAD_DREAMS = 124,

 ABILITIES_COUNT_GEN4 = 125,

// Gen_5
 ABILITY_PICKPOCKET = ABILITIES_COUNT_GEN4,
 ABILITY_SHEER_FORCE = 126,
 ABILITY_CONTRARY = 127,
 ABILITY_UNNERVE = 128, //bad in game buffing with og pressure effect of additional pp useage, leans into unnerving aura idea
 ABILITY_DEFIANT = 129,
 ABILITY_DEFEATIST = 130,
 ABILITY_CURSED_BODY = 131,
 ABILITY_HEALER = 132,
 ABILITY_FRIEND_GUARD = 133,
 ABILITY_WEAK_ARMOR = 134,
 ABILITY_HEAVY_METAL = 135, //potentially boost power of steel type moves?
 ABILITY_LIGHT_METAL = 136, //potentially boost priority of steel type moves
 ABILITY_MULTISCALE = 137,
 ABILITY_TOXIC_BOOST = 138,
 ABILITY_FLARE_BOOST = 139,
 ABILITY_HARVEST = 140,
 ABILITY_TELEPATHY = 141,
 ABILITY_MOODY = 142,
 ABILITY_OVERCOAT = 143,
 ABILITY_POISON_TOUCH = 144,
 ABILITY_REGENERATOR = 145,
 ABILITY_BIG_PECKS = 146,
 ABILITY_SAND_RUSH = 147,
 ABILITY_WONDER_SKIN = 148,
 ABILITY_ANALYTIC = 149,
 ABILITY_ILLUSION = 150,
 ABILITY_IMPOSTER = 151, //remeber check todo list for plan for this, setup extra case effect for wilds i.e only mon in party effect
 ABILITY_INFILTRATOR = 152,
 ABILITY_MUMMY = 153,
 ABILITY_MOXIE = 154,
 ABILITY_JUSTIFIED = 155,
 ABILITY_RATTLED = 156,
 ABILITY_MAGIC_BOUNCE = 157,
 ABILITY_SAP_SIPPER = 158,
 ABILITY_PRANKSTER = 159,
 ABILITY_SAND_FORCE = 160,
 ABILITY_IRON_BARBS = 161,
 ABILITY_ZEN_MODE = 162,
 ABILITY_VICTORY_STAR = 163,
 ABILITY_TURBOBLAZE = 164,
 ABILITY_TERAVOLT = 165,

 ABILITIES_COUNT_GEN5 = 166,

// Gen_6
 ABILITY_AROMA_VEIL = ABILITIES_COUNT_GEN5,
 ABILITY_FLOWER_VEIL = 167,
 ABILITY_CHEEK_POUCH = 168,
 ABILITY_PROTEAN = 169,
 ABILITY_FUR_COAT = 170,
 ABILITY_MAGICIAN = 171,
 ABILITY_BULLETPROOF = 172,
 ABILITY_COMPETITIVE = 173,
 ABILITY_STRONG_JAW = 174,
 ABILITY_REFRIGERATE = 175,
 ABILITY_SWEET_VEIL = 176,
 ABILITY_STANCE_CHANGE = 177,
 ABILITY_GALE_WINGS = 178,
 ABILITY_MEGA_LAUNCHER = 179,
 ABILITY_GRASS_PELT = 180,
 ABILITY_SYMBIOSIS = 181,
 ABILITY_TOUGH_CLAWS = 182,
 ABILITY_PIXILATE = 183,
 ABILITY_GOOEY = 184,
 ABILITY_AERILATE = 185,
 ABILITY_PARENTAL_BOND = 186,
 ABILITY_DARK_AURA = 187,
 ABILITY_FAIRY_AURA = 188,
 ABILITY_AURA_BREAK = 189,
 ABILITY_PRIMORDIAL_SEA = 190,
 ABILITY_DESOLATE_LAND = 191,
 ABILITY_DELTA_STREAM = 192,

 ABILITIES_COUNT_GEN6 = 193,

// Gen_7
 ABILITY_STAMINA = ABILITIES_COUNT_GEN6,
 ABILITY_WIMP_OUT = 194,
 ABILITY_EMERGENCY_EXIT = 195,
 ABILITY_WATER_COMPACTION = 196,
 ABILITY_MERCILESS = 197,
 ABILITY_SHIELDS_DOWN = 198,
 ABILITY_STAKEOUT = 199,
 ABILITY_WATER_BUBBLE = 200,
 ABILITY_STEELWORKER = 201,
 ABILITY_BERSERK = 202,
 ABILITY_SLUSH_RUSH = 203,
 ABILITY_LONG_REACH = 204,
 ABILITY_LIQUID_VOICE = 205,
 ABILITY_TRIAGE = 206,
 ABILITY_GALVANIZE = 207,
 ABILITY_SURGE_SURFER = 208,
 ABILITY_SCHOOLING = 209,
 ABILITY_DISGUISE = 210,
 ABILITY_BATTLE_BOND = 211,
 ABILITY_POWER_CONSTRUCT = 212,
 ABILITY_CORROSION = 213,
 ABILITY_COMATOSE = 214,
 ABILITY_QUEENLY_MAJESTY = 215,
 ABILITY_INNARDS_OUT = 216,
 ABILITY_DANCER = 217,
 ABILITY_BATTERY = 218, //dex entry charjabug it power up vikavolt so does version of commander of tatsugiri want do just for charjabug
 ABILITY_FLUFFY = 219,
 ABILITY_DAZZLING = 220,
 ABILITY_SOUL_HEART = 221,
 ABILITY_TANGLING_HAIR = 222,
 ABILITY_RECEIVER = 223,
 ABILITY_POWER_OF_ALCHEMY = 224,
 ABILITY_BEAST_BOOST = 225,
 ABILITY_RKS_SYSTEM = 226,
 ABILITY_ELECTRIC_SURGE = 227,
 ABILITY_PSYCHIC_SURGE = 228,
 ABILITY_MISTY_SURGE = 229,
 ABILITY_GRASSY_SURGE = 230,
 ABILITY_FULL_METAL_BODY = 231,
 ABILITY_SHADOW_SHIELD = 232,
 ABILITY_PRISM_ARMOR = 233,
 ABILITY_NEUROFORCE = 234,

 ABILITIES_COUNT_GEN7 = 235,

// Gen_8
 ABILITY_INTREPID_SWORD = ABILITIES_COUNT_GEN7,
 ABILITY_DAUNTLESS_SHIELD = 236,
 ABILITY_LIBERO = 237,
 ABILITY_BALL_FETCH = 238,
 ABILITY_COTTON_DOWN = 239,
 ABILITY_PROPELLER_TAIL = 240,
 ABILITY_MIRROR_ARMOR = 241,
 ABILITY_GULP_MISSILE = 242,
 ABILITY_STALWART = 243,
 ABILITY_STEAM_ENGINE = 244,
 ABILITY_PUNK_ROCK = 245,
 ABILITY_SAND_SPIT = 246,
 ABILITY_ICE_SCALES = 247,
 ABILITY_RIPEN = 248,
 ABILITY_ICE_FACE = 249,
 ABILITY_POWER_SPOT = 250,
 ABILITY_MIMICRY = 251,
 ABILITY_SCREEN_CLEANER = 252,
 ABILITY_STEELY_SPIRIT = 253,
 ABILITY_PERISH_BODY = 254,
 ABILITY_WANDERING_SPIRIT = 255,
 ABILITY_GORILLA_TACTICS = 256,
 ABILITY_NEUTRALIZING_GAS = 257,
 ABILITY_PASTEL_VEIL = 258,
 ABILITY_HUNGER_SWITCH = 259,
 ABILITY_QUICK_DRAW = 260,
 ABILITY_UNSEEN_FIST = 261,
 ABILITY_CURIOUS_MEDICINE = 262,
 ABILITY_TRANSISTOR = 263,
 ABILITY_DRAGONS_MAW = 264,
 ABILITY_CHILLING_NEIGH = 265,
 ABILITY_GRIM_NEIGH = 266,
 ABILITY_AS_ONE_ICE_RIDER = 267,
 ABILITY_AS_ONE_SHADOW_RIDER = 268,

ABILITIES_COUNT_GEN8 = 269,

// Gen_9
 ABILITY_LINGERING_AROMA = ABILITIES_COUNT_GEN8,
 ABILITY_SEED_SOWER = 270,
 ABILITY_THERMAL_EXCHANGE = 271,
 ABILITY_ANGER_SHELL = 272,
 ABILITY_PURIFYING_SALT = 273,
 ABILITY_WELL_BAKED_BODY = 274,
 ABILITY_WIND_RIDER = 275,
 ABILITY_GUARD_DOG = 276,
 ABILITY_ROCKY_PAYLOAD = 277,
 ABILITY_WIND_POWER = 278,
 ABILITY_ZERO_TO_HERO = 279,
 ABILITY_COMMANDER = 280,
 ABILITY_ELECTROMORPHOSIS = 281,
 ABILITY_PROTOSYNTHESIS = 282,
 ABILITY_QUARK_DRIVE = 283,
 ABILITY_GOOD_AS_GOLD = 284,
 ABILITY_VESSEL_OF_RUIN = 285,
 ABILITY_SWORD_OF_RUIN = 286,
 ABILITY_TABLETS_OF_RUIN = 287,
 ABILITY_BEADS_OF_RUIN = 288,
 ABILITY_ORICHALCUM_PULSE = 289,
 ABILITY_HADRON_ENGINE = 290,
 ABILITY_OPPORTUNIST = 291,
 ABILITY_CUD_CHEW = 292,
 ABILITY_SHARPNESS = 293,
 ABILITY_SUPREME_OVERLORD = 294,
 ABILITY_COSTAR = 295,
 ABILITY_TOXIC_DEBRIS = 296,
 ABILITY_ARMOR_TAIL = 297,
 ABILITY_EARTH_EATER = 298,
 ABILITY_MYCELIUM_MIGHT = 299,
 ABILITY_HOSPITALITY = 300,
 ABILITY_MINDS_EYE = 301,
 ABILITY_EMBODY_ASPECT_TEAL_MASK = 302,
 ABILITY_EMBODY_ASPECT_HEARTHFLAME_MASK = 303,
 ABILITY_EMBODY_ASPECT_WELLSPRING_MASK = 304,
 ABILITY_EMBODY_ASPECT_CORNERSTONE_MASK = 305,
 ABILITY_TOXIC_CHAIN = 306,
 ABILITY_SUPERSWEET_SYRUP = 307,
 ABILITY_TERA_SHIFT = 308,
 ABILITY_TERA_SHELL = 309,
 ABILITY_TERAFORM_ZERO = 310,   //alter make also break all other terra and long as on field no one else can use terra does default cloud = 9, w terrain clear idk can't tell if it removes them or not maybe it does?
 ABILITY_POISON_PUPPETEER = 311,

 ABILITIES_COUNT_GEN9 = 312,

//CUSTOM ABILITIES
 ABILITY_DISPIRIT_GUARD = ABILITIES_COUNT_GEN9,
 ABILITY_NUISANCE = 313,		//can't remember original plan for this, but I effectively made better prankster..
 ABILITY_MULTI_TASK = 314,
 ABILITY_SIROCCO = 315,
 ABILITY_HI_PRESSURE = 316,
 ABILITY_CUPIDS_ARROW = 317,
 ABILITY_BATTLE_MATRON = 318,
 ABILITY_LIQUID_SOUL = 319,
 ABILITY_OCEAN_MEMORY = 320,
 ABILITY_OVERCHARGE = 321,
 ABILITY_PHOTOSYNTHESIZE = 322,
 ABILITY_GLACIAL_ICE = 323,	//fire immunity + ice body effect	REGICE ability
 ABILITY_LAVA_FISSURE = 324, // pending heatran ability
 ABILITY_TOADSTOOL_NYMPH = 325, // pending Shiinotic ability
 ABILTY_UNKNOWN_POWER = 326,	//unown specific ability similar to plus minus but if partner is unown
 ABILITY_PURIFYING_AURA = 327, //Suicune ability  mix of healer & shedskin but gauranteed
 ABILITY_SQUALL = 328,	//temp versions of drizzle/drought
 ABILITY_SUN_DISK = 329,
 ABILITY_TOUGH_SPINES = 330,	//rough skin for grass types spines can also be bone/spikes
 ABILITY_EROSION = 331,	//regirock ability, rock absorb also absorbs stealth rocks on switchin
 ABILITY_LIQUID_METAL = 332,	//Registeel exclusive 
 ABILITY_MUSCLE_MAGIC = 333,
 ABILITY_TIGER_CUB = 334,	//tinted lens copy
 ABILITY_TIGER_MOM = 335,	//alt version intimidate, drops defense instead of atk, defense drop may be too strong, instead consider speed drop, idea still works, tiger mom pressures you so you cant make a decision i.e lowering your speed
 ABILITY_DARK_DEAL = 336,   //
 ABILITY_CORRUPTION = 337,   //anti heal switch in ability,  users corrupted influence spreads decay, preventing foe from healing, giving to guzzlord etc. make side based effect
 ABILITY_BANDIT_KING = 338,   //embargo on switch in
 ABILITY_AVIATOR = 339,   //Usually flying type, an experienced flyer who's speed can't be lowered  flying version of run away //ok change what will do is make class of ability that gives all benefits of type based bonus, aviator will give all benefits flying types get
 ABILITY_USURPER = 340,	//NEW giratina base ability
 ABILITY_INVERSE_WORLD = 341,	//NEW giratina origin ability
 ABILITY_SONAR = 342,	//sound move boost for bat pokemon,  double move damage, mostly to make sonic boom do dragon breath damage, and be strong early HA only
 ABILITY_ECOSYSTEM = 343,		//MEGA torterra excluive
 ABILITY_ABSOLUTE_ZERO = 344,		//kyurem excluive
 ABILITY_FEATHER_JACKET = 345,	//hisuian decidueye inspired by dex entry and smisonian arcticle cold climate birds have "They had fluffier jackets" to insulate them from cold
 ABILITY_POISONED_LEGACY = 346, // poison pinch ability, for poipoile as its technically a starter,  inspired by marriagetoxin manga, boost poison in a pinch and if poison target will be bad poison consider set to turn = 45, so it does full dmg = 44,st turn
 ABILITY_JEWEL_METABOLISM = 347, //can't think of a name right now, this is just a sableye rock absorb based on dex entry, hmm maybe do more boost damage to rock types? ok, instead of raising hp, boosts def as eaten rocks form more crystals ok i like that
 ABILITY_INVERSION = 348, //  - for ditto  - still to do - mostly works now 
 ABILITY_WETIKO = 349, // for my version crabominable mix of refrigerate & regenerator
 ABILITY_EMPATH = 350, // upgraded synchronize, copies stat change too, not for umbreon psychic only
 ABILITY_EMPATHIC_CURSE = 351, //ability for Mespirit - synchronize with dmg reflect
 ABILITY_INTHRALL = 352, //ability for Uxie - anticipation except it seals the move so it can't be used/selected  //magician conditions, anticipation function logic
 ABILITY_IRON_WILL = 353, //abillity for Azelf - mix of pressure where it can paralyze the attacker, but lower odds, as thye also have to break will pressure odds that lower dmg done
 ABILITY_LIVEWIRE = 354, //for rotom base, weaker version of transistor
 ABILITY_GALEFORCE = 355,
 ABILITY_LETHAL_LEGS = 356, //hitmonlee ability boost kicking moves
 ABILITY_TOXUNGUE = 357,    //Likitung line signature paralytic poison touch
 ABILITY_OMNIPOTENT_AIDE = 358,//for Fraeyjta, can use healing moves for itself, but transfers any heal it would receive to battle partner (if heal target mon with this ability change target to battle partner, otherwise fail)
                                    //if this mon uses a healing move its priority gets increased long as it has a living battle partner, for balanve remove priority effect if status = 44,,  logic is ABILITY_TRIAGE 
                                    //heal priority setup, target swap is not working yet - look at lightning rod?
 ABILITY_FLUORESCENCE = 359,     
 ABILITY_SPECTRE = 360,  //latios & latias ability raise evasiveness on switch in
 ABILITY_AURA_OF_LIGHT = 361,//CRESELIA ABILITY prevent sleep for self and allies, plus reduce dark damage on side - done setup
 ABILITY_DESPAIR = 362, //nother idea true anti heal, gbattlemovedamage *-1  if attempts to heal re-reverses damage formula, so it causes you to take damage instead. 
                                    //give to darkrai //use stringutil to change strings ids like intimidate angerpoint etc. //think put in bigroot function, heal commands and sleep end turn
 ABILITY_RISING_PHOENIX = 363, //MOLTRES ability,  slight DxD reference
 ABILITY_DREAD_WING = 364, //aka burnout GALARIAN MOLTRES ABILITY, tweaking status to fit, set similar to unaware, when attacknig lower enemy def/sp def when target lower foe attack
                            //should be equivalent to amount of = 1, stat stage drop
 ABILITY_PLAGUE_WINGS = 365, //butterfree ability, effect spore no contect, work like powder move, grass immune
 ABILITY_PHANTOM_TOUCH = 366,  //cubone line, contact only scrappy
 ABILITY_APOTHEOSCENT = 367,  //immune to affect of being confused like bugs, and prevent acc drop  for mon w extra senses, fightnig psychic ghost insinct etc.
                                    //planned for parasect if made grass ghost, so still keep bug type confuse exclusion
 ABILITY_WEIGHTED_GI = 368,     //dbz themed in a pinch fighting abiility, boost speed throwing off weights in a pinch boost = 1,.5x or = 2,x, give to bulky fighting types and mienshoo line (based on dex entry)
 ABILITY_VOLT_DASH = 369,       //thunderous therian ability volt absorb + speed boost
 ABILITY_IMMUTABLE_WIND = 370,   //Tornadus therian ability, neutralizing gas + wonder skin

 ABILITY_EVERGREEN = 371,   //celebi ability
 ABILITY_SHAMAN_CURE = 372, //shaman base ability
 ABILITY_UNCHAINED_MELODY = 373,  //NORMAL MOVES into sound moves
 ABILITY_ENAMEL = 374,
 ABILITY_BONE_ARMOR = 375,  //abilities for faedentin and bone fairy evo, //cuts fire damage, bone armor also has force switch prevention, think also recoil?
 ABILITY_STORM_BREAK = 376, //old cloud nine effect, by for flying types, pretty much delta stream but just to break weather have to find birds I have space to give this to
 ABILITY_SPACE_CONTROL = 377, //hmm domain expansion? nah too long, palkia ability uses portals to make moves = 100,% accurate and is immune to ice because adapted to void of space
 ABILITY_COLD_EMBRACE = 378,    //froslass ability 
 ABILITY_TOXIC_WING = 379,
 ABILITY_TIME_CONTROL = 380, //new dialga ability
 ABILITY_TORCHSOUL = 381, //fire affinity ability, embroar
 ABILITY_GRUNGE = 382,  //poison affinity / can't be poisoned should also give poison boost? or should I go more creative give all moves chance to poison?
 ABILITY_SWIFT_JUSTICE = 383, //virizion new ability boost damage if move first
 ABILITY_TOOLS_OF_THE_TRADE = 384, //FATE reference //new ability for spidops combine insomnia stakeout analytic and guts/defiant but weaker effects for all if only sleeps one turn could boost defense and get heal? if heal doesn't work just block sleep altogether
 ABILITY_TROJAN_SWORD = 385,  //idea for buff iron leaves, block intimidate and gives sharpness
 ABILITY_HEAT_TRANCE = 386, //SCOVILLAIN capsakid buff burn healing since is fire type still not great as requires holding flame orb guess can fing it if I don't need it?
 ABILITY_DESERT_DWELLER = 387, //new cacturne line ability heat proof + thick fat
 ABILITY_FAIRY_MIST = 388, //for iron valiant combine misty surge w pixilate
 ABILITY_COMPASS = 389, //no guard clone for onix nosepass binacle as designed around compasses
 ABILITY_HANDS_OF_FATE = 390, //purifying salt clone for binacle as designed around hamsa protective ward against the evil eye, think also give specific immunity to shadow tag mean look and decidueye move
 ABILITY_DUST_DEVIL = 391, //combine sandstream & wind rider for new bug psuedo
 ABILITY_PLASMA_OVERDRIVE = 392, //custom moldbreaker lightningrod flash fire for zekrom/reshiram fusion
 ABILITY_CREATION_ENGINE = 393, //custom ability for original dragon //power over fire electricity and ice  //consider rename to creation engine as zek resh based aruond turbine
 ABILITY_DARK_CORONA = 394, //initial intended ability for larvalking tough spines + poison point
 ABILITY_LUNAR_SOLSTICE = 395, //moon version of sundisk
 ABILITY_LUNAR_POWER = 396, //moon version of solar power //think may add on can't be damaged by moon based attacks? like balistic
 ABILITY_NEW_MOON = 397, //heal by moonlight think also heal from taking moon based attacks?
 ABILITY_TOXIC_DELUGE = 398,  //acid rain ability
 ABILITY_RESOLUTE = 399,  //planned ability for lokix to enter showdown mode same idea as ash greninja
 ABILITY_PIERCING_HORN = 400,
 ABILITY_X_SIGHT = 401, //luxray new signature ability frisk plus bypass acc check when above half hp, as dex entry says its xray vision requires a lot of energy
 ABILITY_PRECISE_STRIKE = 402, //fighting version of sniper, for storm throw buff
 ABILITY_BRAVERY = 403,  //keldeo version justified
 ABILITY_FUGUE = 404,   //wow this being = 404, is so appropriate lmao, malamar new signature ability confusion & sleep always max turns
 ABILITY_CRYOSTORM = 405, //for separating hail ability from snow ability
 ABILITY_SECRET_ARTS = 406, //shadow mega greninja ability part no guard part unseen fist to break protect and guard
 ABILITY_REIKI = 407, //mega mewtwo x ability inner focus + scrappy
 ABILITY_AURORA_SHIFT = 408, //deoxys defense ability
 ABILITY_DETERMINATION = 409, //idea from Opal speed boost version of moxie think give tyrogue fighing type
 ABILITY_POET_ARTIST = 410,
ABILITIES_COUNT_CUSTOM,

 ABILITIES_COUNT = ABILITIES_COUNT_CUSTOM, //   ability count is last ability number +, since we have to count ability,
};

#endif  // GUARD_CONSTANTS_ABILITIES_H
