#ifndef GUARD_CONSTANTS_PARTY_MENU_H
#define GUARD_CONSTANTS_PARTY_MENU_H

#define PC_MON_CHOSEN 0xFE
//NEEDED to include in event_scripts.s
//for constant to be recognized
#define PARTY_NOTHING_CHOSEN 0xFF

#define AILMENT_NONE  0
#define AILMENT_PSN   1
#define AILMENT_PRZ   2
#define AILMENT_SLP   3
#define AILMENT_FRZ   4
#define AILMENT_BRN   5 
#define AILMENT_INF   6
#define AILMENT_PKRS  7
#define AILMENT_FNT   8
#define EXP_SHARE_ON  9   //for spirit lock, but seems letters here somewhat determine what's displayed on hp menu, so kept to 4.
#define EXP_NULL_ON  10
//staus gfx order -cut sprt lock, not doing
//psn, prz, sleep, freez, burn, infest, pkrs, fnt, exp share, exp null

#define TUTOR_MOVE_MEGA_PUNCH      0
#define TUTOR_MOVE_SWORDS_DANCE    1
#define TUTOR_MOVE_MEGA_KICK       2
#define TUTOR_MOVE_BODY_SLAM       3
#define TUTOR_MOVE_DOUBLE_EDGE     4
#define TUTOR_MOVE_COUNTER         5
#define TUTOR_MOVE_SEISMIC_TOSS    6
#define TUTOR_MOVE_MIMIC           7
#define TUTOR_MOVE_METRONOME       8
#define TUTOR_MOVE_SOFT_BOILED     9
#define TUTOR_MOVE_DREAM_EATER     10
#define TUTOR_MOVE_THUNDER_WAVE    11
#define TUTOR_MOVE_EXPLOSION       12
#define TUTOR_MOVE_ROCK_SLIDE      13
#define TUTOR_MOVE_SUBSTITUTE      14
#define TUTOR_MOVE_COUNT           15 // regular tutor move count

#define TUTOR_MOVE_FRENZY_PLANT    15
#define TUTOR_MOVE_BLAST_BURN      16
#define TUTOR_MOVE_HYDRO_CANNON    17

//had to reorder list to match item hms
#define FIELD_MOVE_CUT          0//1    //was misty - now brock
#define FIELD_MOVE_FLY          1//2    //was surge - now koga
#define FIELD_MOVE_SURF         2//4    //was koga - now misty
#define FIELD_MOVE_STRENGTH     3       //erika
#define FIELD_MOVE_FLASH        4//0    //was brock  - now surge
#define FIELD_MOVE_ROCK_SMASH   5
#define FIELD_MOVE_WATERFALL    6
#define FIELD_MOVE_DIVE         7
#define FIELD_MOVE_ROCK_CLIMB   8
#define FIELD_MOVE_TELEPORT     9
#define FIELD_MOVE_DIG          10
#define FIELD_MOVE_MILK_DRINK   11
#define FIELD_MOVE_SOFT_BOILED  12
#define FIELD_MOVE_SWEET_SCENT  13
#define FIELD_MOVE_END          14

#define PARTY_LAYOUT_SINGLE          0
#define PARTY_LAYOUT_DOUBLE          1
#define PARTY_LAYOUT_MULTI           2
#define PARTY_LAYOUT_MULTI_SHOWCASE  3  // The layout during the screen that appears just before a multi battle
#define PARTY_LAYOUT_COUNT           4
#define KEEP_PARTY_LAYOUT            0xFF

enum PartyMenuType {
PARTY_MENU_TYPE_FIELD, 
PARTY_MENU_TYPE_IN_BATTLE, 
PARTY_MENU_TYPE_CONTEST, 
PARTY_MENU_TYPE_CHOOSE_MON, 
PARTY_MENU_TYPE_CHOOSE_HALF,  // multi battles, eReader battles, and some battle facilities
PARTY_MENU_TYPE_MULTI_SHOWCASE,
PARTY_MENU_TYPE_DAYCARE, 
PARTY_MENU_TYPE_MOVE_RELEARNER, 
PARTY_MENU_TYPE_UNION_ROOM_REGISTER,  // trading board
PARTY_MENU_TYPE_UNION_ROOM_TRADE,  // trading board
PARTY_MENU_TYPE_SPIN_TRADE, // Unused beta for Gen IV's Spin Trade
PARTY_MENU_TYPE_MINIGAME,
};

enum PartyAction {
PARTY_ACTION_CHOOSE_MON,
PARTY_ACTION_SEND_OUT,
PARTY_ACTION_CANT_SWITCH,
PARTY_ACTION_USE_ITEM,
PARTY_ACTION_ABILITY_PREVENTS,
PARTY_ACTION_GIVE_ITEM,  
PARTY_ACTION_GIVE_PC_ITEM,
PARTY_ACTION_GIVE_MAILBOX_MAIL,
PARTY_ACTION_SWITCH,
PARTY_ACTION_SWITCHING,
PARTY_ACTION_SOFTBOILED,
PARTY_ACTION_CHOOSE_AND_CLOSE,
PARTY_ACTION_MOVE_TUTOR,
PARTY_ACTION_MINIGAME,
PARTY_ACTION_REUSABLE_ITEM,
};

// IDs for DisplayPartyMenuStdMessage, to display the message at the bottom of the party menu
enum PartyMsg {

PARTY_MSG_CHOOSE_MON,
PARTY_MSG_CHOOSE_MON_OR_CANCEL,
PARTY_MSG_CHOOSE_MON_AND_CONFIRM,
PARTY_MSG_MOVE_TO_WHERE, 
PARTY_MSG_TEACH_WHICH_MON,
PARTY_MSG_USE_ON_WHICH_MON,
PARTY_MSG_GIVE_TO_WHICH_MON,
PARTY_MSG_NOTHING_TO_CUT,
PARTY_MSG_CANT_SURF_HERE,
PARTY_MSG_ALREADY_SURFING,
PARTY_MSG_CURRENT_TOO_FAST,
PARTY_MSG_ENJOY_CYCLING,
PARTY_MSG_ALREADY_IN_USE,
PARTY_MSG_CANT_USE_HERE,
PARTY_MSG_NO_MON_FOR_BATTLE,
PARTY_MSG_CHOOSE_MON_2,
PARTY_MSG_NOT_ENOUGH_HP,
PARTY_MSG_THREE_MONS_ARE_NEEDED,
PARTY_MSG_TWO_MONS_ARE_NEEDED,
PARTY_MSG_MONS_CANT_BE_SAME,
PARTY_MSG_NO_SAME_HOLD_ITEMS,
PARTY_MSG_UNUSED,
PARTY_MSG_DO_WHAT_WITH_MON,
PARTY_MSG_RESTORE_WHICH_MOVE,
PARTY_MSG_BOOST_PP_WHICH_MOVE,
PARTY_MSG_DO_WHAT_WITH_ITEM,
PARTY_MSG_DO_WHAT_WITH_MAIL,
PARTY_MSG_HATCH_THIS_EGG,
PARTY_MSG_ALLOW_TO_EVOLVE,
PARTY_MSG_NONE = 127,

};


// IDs for DisplayPartyPokemonDescriptionText, to display a message in the party pokemon's box
#define PARTYBOX_DESC_NO_USE      0
#define PARTYBOX_DESC_ABLE_3      1
#define PARTYBOX_DESC_FIRST       2
#define PARTYBOX_DESC_SECOND      3
#define PARTYBOX_DESC_THIRD       4
#define PARTYBOX_DESC_ABLE        5
#define PARTYBOX_DESC_NOT_ABLE    6
#define PARTYBOX_DESC_ABLE_2      7
#define PARTYBOX_DESC_NOT_ABLE_2  8
#define PARTYBOX_DESC_LEARNED     9

enum SelectionWindow
{
SELECTWINDOW_ACTIONS,
SELECTWINDOW_ITEM,
SELECTWINDOW_MAIL,
SELECTWINDOW_MOVES,
SELECTWINDOW_HATCH,
SELECTWINDOW_EVOSTATE,
};

#endif // GUARD_CONSTANTS_PARTY_MENU_H
