#ifndef GUARD_CONSTANTS_TRAINERS_H
#define GUARD_CONSTANTS_TRAINERS_H

#include "constants/opponents.h"

#define TRAINER_ENCOUNTER_MUSIC_MALE         0 // standard male encounter music
#define TRAINER_ENCOUNTER_MUSIC_FEMALE       1 // standard female encounter music
#define TRAINER_ENCOUNTER_MUSIC_GIRL         2 // used for male Tubers and Young Couples too
#define TRAINER_ENCOUNTER_MUSIC_SUSPICIOUS   3
#define TRAINER_ENCOUNTER_MUSIC_INTENSE      4
#define TRAINER_ENCOUNTER_MUSIC_COOL         5
#define TRAINER_ENCOUNTER_MUSIC_AQUA         6
#define TRAINER_ENCOUNTER_MUSIC_MAGMA        7
#define TRAINER_ENCOUNTER_MUSIC_SWIMMER      8
#define TRAINER_ENCOUNTER_MUSIC_TWINS        9 // used for other trainer classes too
#define TRAINER_ENCOUNTER_MUSIC_ELITE_FOUR  10
#define TRAINER_ENCOUNTER_MUSIC_HIKER       11 // used for other trainer classes too
#define TRAINER_ENCOUNTER_MUSIC_INTERVIEWER 12
#define TRAINER_ENCOUNTER_MUSIC_RICH        13 // Rich Boys and Gentlemen

//attempt match EE idk if will work
enum __attribute__((packed)) TrainerPicID
{
 TRAINER_PIC_AQUA_LEADER_ARCHIE,
 TRAINER_PIC_AQUA_GRUNT_M,
 TRAINER_PIC_AQUA_GRUNT_F,
 TRAINER_PIC_RS_AROMA_LADY,
 TRAINER_PIC_RS_RUIN_MANIAC,
 TRAINER_PIC_INTERVIEWER,
 TRAINER_PIC_RS_TUBER_F,
 TRAINER_PIC_RS_TUBER_M,
 TRAINER_PIC_RS_COOLTRAINER_M,
 TRAINER_PIC_RS_COOLTRAINER_F,
 TRAINER_PIC_HEX_MANIAC,
 TRAINER_PIC_RS_LADY,
 TRAINER_PIC_RS_BEAUTY,
 TRAINER_PIC_RICH_BOY,
 TRAINER_PIC_RS_POKEMANIAC,
 TRAINER_PIC_RS_SWIMMER_M,
 TRAINER_PIC_RS_BLACK_BELT,
 TRAINER_PIC_GUITARIST,
 TRAINER_PIC_KINDLER,
 TRAINER_PIC_RS_CAMPER,
 TRAINER_PIC_BUG_MANIAC,
 TRAINER_PIC_RS_PSYCHIC_M,
 TRAINER_PIC_RS_PSYCHIC_F,
 TRAINER_PIC_RS_GENTLEMAN,
 TRAINER_PIC_ELITE_FOUR_SIDNEY,
 TRAINER_PIC_ELITE_FOUR_PHOEBE,
 TRAINER_PIC_LEADER_ROXANNE,
 TRAINER_PIC_LEADER_BRAWLY,
 TRAINER_PIC_LEADER_TATE_AND_LIZA,
 TRAINER_PIC_SCHOOL_KID_M,
 TRAINER_PIC_SCHOOL_KID_F,
 TRAINER_PIC_SR_AND_JR,
 TRAINER_PIC_POKEFAN_M,
 TRAINER_PIC_POKEFAN_F,
 TRAINER_PIC_EXPERT_M,
 TRAINER_PIC_EXPERT_F,
 TRAINER_PIC_RS_YOUNGSTER,
 TRAINER_PIC_CHAMPION_STEVEN,
 TRAINER_PIC_RS_FISHERMAN,
 TRAINER_PIC_CYCLING_TRIATHLETE_M,
 TRAINER_PIC_CYCLING_TRIATHLETE_F,
 TRAINER_PIC_RUNNING_TRIATHLETE_M,
 TRAINER_PIC_RUNNING_TRIATHLETE_F,
 TRAINER_PIC_SWIMMING_TRIATHLETE_M,
 TRAINER_PIC_SWIMMING_TRIATHLETE_F,
 TRAINER_PIC_DRAGON_TAMER,
 TRAINER_PIC_RS_BIRD_KEEPER,
 TRAINER_PIC_NINJA_BOY,
 TRAINER_PIC_BATTLE_GIRL,
 TRAINER_PIC_PARASOL_LADY,
 TRAINER_PIC_RS_SWIMMER_F,
 TRAINER_PIC_RS_PICNICKER,
 TRAINER_PIC_RS_TWINS,
 TRAINER_PIC_RS_SAILOR,
 TRAINER_PIC_COLLECTOR,
 TRAINER_PIC_WALLY,
 TRAINER_PIC_RS_BRENDAN_1,
 TRAINER_PIC_RS_MAY_1,
 TRAINER_PIC_RS_POKEMON_BREEDER_M,
 TRAINER_PIC_RS_POKEMON_BREEDER_F,
 TRAINER_PIC_RS_POKEMON_RANGER_M,
 TRAINER_PIC_RS_POKEMON_RANGER_F,
 TRAINER_PIC_MAGMA_LEADER_MAXIE,
 TRAINER_PIC_MAGMA_GRUNT_M,
 TRAINER_PIC_MAGMA_GRUNT_F,
 TRAINER_PIC_RS_LASS,
 TRAINER_PIC_RS_BUG_CATCHER,
 TRAINER_PIC_RS_HIKER,
 TRAINER_PIC_RS_YOUNG_COUPLE,
 TRAINER_PIC_OLD_COUPLE,
 TRAINER_PIC_RS_SIS_AND_BRO,
 TRAINER_PIC_AQUA_ADMIN_M,
 TRAINER_PIC_AQUA_ADMIN_F,
 TRAINER_PIC_MAGMA_ADMIN_M,
 TRAINER_PIC_MAGMA_ADMIN_F,
 TRAINER_PIC_LEADER_WATTSON,
 TRAINER_PIC_LEADER_FLANNERY,
 TRAINER_PIC_LEADER_NORMAN,
 TRAINER_PIC_LEADER_WINONA,
 TRAINER_PIC_LEADER_WALLACE,
 TRAINER_PIC_ELITE_FOUR_GLACIA,
 TRAINER_PIC_ELITE_FOUR_DRAKE,
 TRAINER_PIC_YOUNGSTER,
 TRAINER_PIC_BUG_CATCHER,
 TRAINER_PIC_LASS,
 TRAINER_PIC_SAILOR,
 TRAINER_PIC_CAMPER,
 TRAINER_PIC_PICNICKER,
 TRAINER_PIC_POKEMANIAC,
 TRAINER_PIC_SUPER_NERD,
 TRAINER_PIC_HIKER,
 TRAINER_PIC_BIKER,
 TRAINER_PIC_BURGLAR,
 TRAINER_PIC_ENGINEER,
 TRAINER_PIC_FISHERMAN,
 TRAINER_PIC_SWIMMER_M,
 TRAINER_PIC_CUE_BALL,
 TRAINER_PIC_GAMBLER,
 TRAINER_PIC_BEAUTY,
 TRAINER_PIC_SWIMMER_F,
 TRAINER_PIC_PSYCHIC_M,
 TRAINER_PIC_ROCKER,
 TRAINER_PIC_JUGGLER,
 TRAINER_PIC_TAMER,
 TRAINER_PIC_BIRD_KEEPER,
 TRAINER_PIC_BLACK_BELT,
 TRAINER_PIC_RIVAL_EARLY,
 TRAINER_PIC_SCIENTIST,
 TRAINER_PIC_LEADER_GIOVANNI,
 TRAINER_PIC_ROCKET_GRUNT_M,
 TRAINER_PIC_COOLTRAINER_M,
 TRAINER_PIC_COOLTRAINER_F,
 TRAINER_PIC_ELITE_FOUR_LORELEI,
 TRAINER_PIC_ELITE_FOUR_BRUNO,
 TRAINER_PIC_ELITE_FOUR_AGATHA,
 TRAINER_PIC_ELITE_FOUR_LANCE,
 TRAINER_PIC_LEADER_BROCK,
 TRAINER_PIC_LEADER_MISTY,
 TRAINER_PIC_LEADER_LT_SURGE,
 TRAINER_PIC_LEADER_ERIKA,
 TRAINER_PIC_LEADER_KOGA,
 TRAINER_PIC_LEADER_SABRINA,
 TRAINER_PIC_LEADER_BLAINE,
 TRAINER_PIC_GENTLEMAN,
 TRAINER_PIC_RIVAL_LATE,
 TRAINER_PIC_CHAMPION_RIVAL,
 TRAINER_PIC_CHANNELER,
 TRAINER_PIC_TWINS,
 TRAINER_PIC_COOL_COUPLE,
 TRAINER_PIC_YOUNG_COUPLE,
 TRAINER_PIC_CRUSH_KIN,
 TRAINER_PIC_SIS_AND_BRO,
 TRAINER_PIC_PROFESSOR_OAK,
 TRAINER_PIC_RS_BRENDAN_2,
 TRAINER_PIC_RS_MAY_2,
 TRAINER_PIC_RED,
 TRAINER_PIC_LEAF,
 TRAINER_PIC_ROCKET_GRUNT_F,
 TRAINER_PIC_PSYCHIC_F,
 TRAINER_PIC_CRUSH_GIRL,
 TRAINER_PIC_TUBER_F,
 TRAINER_PIC_POKEMON_BREEDER_F,
 TRAINER_PIC_POKEMON_RANGER_M,
 TRAINER_PIC_POKEMON_RANGER_F,
 TRAINER_PIC_AROMA_LADY,
 TRAINER_PIC_RUIN_MANIAC,
 TRAINER_PIC_LADY,
 TRAINER_PIC_PAINTER,
 TRAINER_PIC_FRONT_COUNT,
 TRAINER_PIC_BACK_BRENDAN = TRAINER_PIC_FRONT_COUNT, // The player back pics are assumed to alternate according to the gender values (MALE/FEMALE)
 TRAINER_PIC_BACK_MAY,
 TRAINER_PIC_BACK_RED,
 TRAINER_PIC_BACK_LEAF,
 TRAINER_PIC_BACK_RUBY_SAPPHIRE_BRENDAN,
 TRAINER_PIC_BACK_RUBY_SAPPHIRE_MAY,
 TRAINER_PIC_BACK_WALLY,
 TRAINER_PIC_BACK_STEVEN,
 TRAINER_PIC_BACK_POKEDUDE,
 TRAINER_PIC_BACK_OLD_MAN,
 TRAINER_PIC_COUNT,
 TRAINER_PIC_BACK_COUNT = (TRAINER_PIC_COUNT - TRAINER_PIC_FRONT_COUNT),
};


// Special Trainer Ids.
//      0-299 are frontier trainers
#define TRAINER_RECORD_MIXING_FRIEND        0 //FRONTIER_TRAINERS_COUNT
#define TRAINER_RECORD_MIXING_APPRENTICE    400
#define TRAINER_EREADER                     500
#define TRAINER_FRONTIER_BRAIN              1022
#define TRAINER_PLAYER                      1023
#define TRAINER_SECRET_BASE                 1024
#define TRAINER_LINK_OPPONENT               2048
#define TRAINER_UNION_ROOM                  3072


#define F_TRAINER_FEMALE (1 << 7)

// All trainer parties specify the IV, level, and species for each Pokémon in the
// party. Some trainer parties also specify held items and custom moves for each
// Pokémon.
#define F_TRAINER_PARTY_NO_ITEM_DEFAULT_MOVESET 0
#define F_TRAINER_PARTY_CUSTOM_MOVESET (1 << 0)
#define F_TRAINER_PARTY_HELD_ITEM      (1 << 1)

#endif  // GUARD_CONSTANTS_TRAINERS_H
