Route25_SeaCottage_Text_ImBillHelpMeOutPal:: @ 819FDFA
    .string "Hiya! I'm a POKéMON…\n"
    .string "…No I'm not!\p"
    .string "Call me BILL!\n"
    .string "I'm a true-blue POKéMANIAC!\p"
    .string "Hey!\n"
    .string "What's with that skeptical look?\p"
    .string "I'm not joshing you, pal.\p"
    .string "I screwed up an experiment and got\n"
    .string "combined with a POKéMON!\p"
    .string "So, how about it?\n"
    .string "Help me out here!$"

Route25_SeaCottage_Text_ImBillHelpMeOutLady:: @ 819FEE6
    .string "Hiya! I'm a POKéMON…\n"
    .string "…No I'm not!\p"
    .string "Call me BILL!\n"
    .string "I'm a true-blue POKéMANIAC!\p"
    .string "Hey!\n"
    .string "What's with that skeptical look?\p"
    .string "I'm not joshing you, lady.\p"
    .string "I screwed up an experiment and got\n"
    .string "combined with a POKéMON!\p"
    .string "So, how about it?\n"
    .string "Help me out here!$"

Route25_SeaCottage_Text_RunCellSeparationOnPC:: @ 819FFD3
    .string "Wait till I get inside the\n"
    .string "TELEPORTER.\p"
    .string "When I do, go to my PC and run\n"
    .string "the Cell Separation System.$"

@never new these were lines, but 
@I''m gonna do something diabolical just to
@make this equal lol
Route25_SeaCottage_Text_NoPleaseChief:: @ 81A0035
    .string "No!?\n"
    .string "Now don't be so cold!\p"
    .string "Come on, you gotta help a guy in\n"
    .string "deep, deep trouble!\p"
    .string "What do you say, Master~?\n"
    .string "Please?\l"
    .string "Okay?\l"
    .string "All right!$"

Route25_SeaCottage_Text_NoPleaseBeautiful:: @ 81A00B6
    .string "No!?\n"
    .string "Now don't be so cold!\p"
    .string "Come on, you gotta help a guy in\n"
    .string "deep, deep trouble!\p"
    .string "What do you say, beautiful?\n"
    .string "Please?\l"
    .string "Okay?\l"
    .string "All right!$"

@move these scripts to end of cell separator script
@plan try add exclamation point thing from game start on bill
Route25_SeaCottage_Text_ThanksBud:: @ 81A013B
    .string "BILL: Yeehah!\n"
    .string "Thanks, bud! I owe you one!\p"
    .string "So, did you come to see my\n"
    .string "POKéMON collection?\p"
    .string "You didn't?\n"
    .string "That's a bummer.$"    

Route25_SeaCottage_Text_ThanksLady:: @ 81A01E4
    .string "BILL: Yeehah!\n"
    .string "Thanks, lady! I owe you one!\p"
    .string "So, did you come to see my\n"
    .string "POKéMON collection?\p"
    .string "You didn't?\n"
    .string "That's a bummer.$"

Route25_SeaCottage_Text_BillRemembers::
    .string "Oh, that reminds me!$"

Route25_SeaCottage_Text_BillUpdatesPC::
    .string "BILL: Before the accident,\n"
    .string "I was working on an update\l"
    .string "for my PC System.\p"
    .string "Normally POKéMON sent to\n"
    .string "PROF. OAK's ranch gain experience\l"
    .string "and get stronger while there.\p"
    .string "But not every trainer wants\n"
    .string "their POKéMON to be strong\l"
    .string "in the typical way.\p"
    .string "BILL: …\p"
    .string "There we go!\p"
    .string "With this you'll be able to\n"
    .string "send an order to exclude\l"
    .string "your POKéMON from training!$"

Route25_SeaCottage_Text_ThanksAgain::
    .string "BILL: Thanks again for helping me.\n"
    .string "Come here for a sec, I have one\l"
    .string "more thing for you.$"

Route25_SeaCottage_Text_BillGivesTicket::
    .string "BILL: Here, I hope this is\n"
    .string "enough to show my gratitude.$"

Route25_SeaCottage_Text_ReceivedSSTicketFromBill:: @ 81A028E
    .string "{PLAYER} received an S.S. TICKET\n"
    .string "from BILL.$"

Route25_SeaCottage_Text_YouveGotTooMuchStuff:: @ 81A02B4
    .string "You've got too much stuff!$"

Route25_SeaCottage_Text_SSAnnePartyYouGoInstead:: @ 81A02CF
    .string "That cruise ship S.S. ANNE is in\n"
    .string "VERMILION CITY.\p"
    .string "I hear there are lots of TRAINERS\n"
    .string "on board, too.\p"
    .string "They invited me to their party, but\n"
    .string "I can't stand fancy do's.\p"
    .string "Why don't you go instead of me?\n"
    .string "Go on and have a good time.$"

Route25_SeaCottage_Text_CheckOutRareMonsOnPC:: @ 81A03AB
    .string "BILL: Feel like checking out some\n"
    .string "of my rare POKéMON on my PC?\p"
    .string "Go on, check out my PC.$"

Route25_SeaCottage_Text_TeleporterIsDisplayed:: @ 81A0402
    .string "TELEPORTER is displayed on the PC\n"
    .string "monitor.$"

Route25_SeaCottage_Text_InitiatedTeleportersCellSeparator:: @ 81A042D
    .string "{PLAYER} initiated the TELEPORTER's\n"
    .string "Cell Separator.$"

Route25_SeaCottage_Text_BillsFavoriteMonList:: @ 81A045B
    .string "BILL's favorite POKéMON list!$"

Route25_SeaCottage_Text_SeeWhichMon:: @ 81A0479
    .string "Which POKéMON do you want to see?$"

