Route15_WestEntrance_2F_Text_GiveItemIfCaughtEnough:: @ 819F5AB
    .string "Hi! Remember me?\n"
    .string "I'm one of PROF. OAK's AIDES.\p"
    .string "If your POKéDEX has complete data\n"
    .string "on {STR_VAR_1} species, I'm supposed to\l"
    .string "give you a reward.\p"
    .string "PROF. OAK entrusted me with the\n"
    .string "{STR_VAR_2} for you.\p"
    .string "So, {PLAYER}, let me ask you.\p"
    .string "Have you gathered data on at least\n"
    .string "{STR_VAR_1} kinds of POKéMON?$"

Route15_WestEntrance_2F_Text_GreatHereYouGo:: @ 819F6AA
    .string "Great! You have caught or owned\n"
    .string "{STR_VAR_3} kinds of POKéMON!\p"
    .string "Congratulations!\n"
    .string "Here you go!$"

Route15_WestEntrance_2F_Text_ReceivedItemFromAide:: @ 819F6FD
    .string "{PLAYER} received the {STR_VAR_2}\n"
    .string "from the AIDE.$"

@need test
@plan put mega stones in case like tms
Route15_WestEntrance_2F_Text_ExplainMegaRing:: @ 819F71F
    .string "MEGA RING is an item to be used\n"
    .string "by a POKéMON Trainer.\p"
    .string "With a given Mega Stone\n"
    .string "it allows a POKéMON to Mega Evolve!\p"
    .string "An enhanced form that only one\n"
    .string "member of your party may take.\p"
    .string "Your POKéMON doesn't need to hold\n"
    .string "its mega stone to be able to evolve.$"

Route15_WestEntrance_2F_Text_LargeShiningBird:: @ 819F79C
    .string "Let's see what the binoculars have\n"
    .string "to show…\p"
    .string "A large, shining bird is flying\n"
    .string "toward the sea.$"

Route15_WestEntrance_2F_Text_SmallIslandOnHorizon:: @ 819F7F8
    .string "Let's see what the binoculars have\n"
    .string "to show…\p"
    .string "It looks like a small island on\n"
    .string "the horizon!$"

