TwoIsland_House_Text_TeachPlayerForMushroomFee:: @ 81A2B88
    .string "I'm the POKéMON MOVE MANIAC.\p"
    .string "I know every single move that\n"
    .string "POKéMON learn growing up.\p"
    .string "I'm also a mushroom maniac.\p"
    .string "But recently I've wanted\n"
    .string "to try something more unique.\p"
    .string "Unfortunately, Truffles are\.\n"
    .string "quite expensive.\p"
    .string "If you're willing to pay\n"
    .string "a small fee.\p"
    .string "I'll show you how to teach\n"
    .string "moves to your POKéMON.$"

TwoIsland_House_Text_WantMeToTeachMove:: @ 81A2C63
    .string "Well, do you want to learn how\n"
    .string "to teach moves to your POKéMON?\l"
    .string "My fee is ¥{STR_VAR_2}.$"

TwoIsland_House_Text_ComeAgainToRemember:: 
    .string "Come again if you decide you\n"
    .string "want to learn to remember moves.$"

TwoIsland_House_Text_PlayerLearnedToRemember::
    .string "{PLAYER} learned how to teach moves!$"

TwoIsland_House_Text_PlayerHasLearnedToRememberMoves:: @ 81994B1
    .string "Congratulations!\p"
    .string "Now you can have your POKéMON\n"
    .string "remember moves from the pc.$"

TwoIsland_House_Text_ThanksForBuying::
    .string "Thanks again for your patronage.\n"
    .string "My truffe fund is very grateful!$"

TwoIsland_House_Text_TutorWhichMon:: @ 81A2CC3
    .string "Which POKéMON needs tutoring?$"

TwoIsland_House_Text_TeachWhichMove:: @ 81A2CE1
    .string "Which move should I teach?$"

TwoIsland_House_Text_NoMoveICanTeachThatMon:: @ 81A2CFC
    .string "Sorry…\p"
    .string "It doesn't appear as if I have a\n"
    .string "move I can teach that POKéMON.$"

TwoIsland_House_Text_IllNeedMushroomOrTwo:: @ 81A2D43
    .string "Then, I'll need a MUSHROOM or two.\n"
    .string "What are you going to give me?$"

TwoIsland_House_Text_HandedOverTwoTinyMushrooms:: @ 81A2D85
    .string "{PLAYER} handed over two\n"
    .string "TINYMUSHROOMS in exchange.$"

TwoIsland_House_Text_HandedOverOneBigMushroom:: @ 81A2DB3
    .string "{PLAYER} handed over one\n"
    .string "BIG MUSHROOM in exchange.$"

TwoIsland_House_Text_NeedMushroomOrTwoToLearnMove:: @ 81A2DE0
    .string "If your POKéMON need to learn a\n"
    .string "move, I need a MUSHROOM or two.$"

TwoIsland_House_Text_CantTeachAnEgg:: @ 81A2E20
    .string "Hunh? There isn't a single move\n"
    .string "that I can teach an EGG.$"

