PalletTown_PlayersHouse_1F_Text_AllBoysLeaveOakLookingForYou:: @ 818D2F0
    .string "MOM: …Right.\n"
    .string "All boys leave home someday.\l"
    .string "It said so on TV.\p"
    .string "Oh, yes. PROF. OAK, next door, was\n"
    .string "looking for you.$"

PalletTown_PlayersHouse_1F_Text_AllGirlsLeaveOakLookingForYou:: @ 818D360
    .string "MOM: …Right.\n"
    .string "All girls dream of traveling.\l"
    .string "It said so on TV.\p"
    .string "Oh, yes. PROF. OAK, next door, was\n"
    .string "looking for you.$"

PalletTown_PlayersHouse_1F_Text_YouShouldTakeQuickRest:: @ 818D3D1
    .string "MOM: {PLAYER}!\n"
    .string "You should take a quick rest.$"

PalletTown_PlayersHouse_1F_Text_LookingGreatTakeCare:: @ 818D3F8
    .string "MOM: Oh, good! You and your\n"
    .string "POKéMON are looking great.\l"
    .string "Take care now!$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVFourBoysOnRailroad:: @ 818D43E
    .string "There's a movie on TV.\n"
    .string "Four boys are walking on railroad\l"
    .string "tracks.\p"
    .string "…I better go, too.$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVGirlOnBrickRoad:: @ 818D492
    .string "There's a movie on TV.\n"
    .string "A girl with her hair in pigtails is\l"
    .string "walking up a brick road.\p"
    .string "…I better go, too.$"

PalletTown_PlayersHouse_1F_Text_OopsWrongSide:: @ 818D4F9
    .string "Oops, wrong side…$"

PalletTown_PlayersHouse_1F_Text_NearlyForgot::
    .string "MOM: Oh my, I nearly forgot!$"

PalletTown_PlayersHouse_1F_Text_MomsGift::
    .string "Here I got you something.\p"
    .string "The nice man at the mart said\n"
    .string "this item is all the rage!\p"
    .string "MOM: It'll help your POKéMON\n"
    .string "gain EXP!$"

PalletTown_PlayersHouse_1F_Text_ReceiveExpShare::
    .string "MOM: Its an Exp. Share!$"

PalletTown_PlayersHouse_1F_Text_EndingResponse::
    .string "{PLAYER}: …\p"
    .string "MOM: Well hurry on now\n"
    .string "PROF. OAK is waiting.$"
