//Recomendation, if you want to remove things from the tm or hm lists//
//Delete them rather than commenting them out //


static const u16 sUniversalMoves[] =
{
    MOVE_BIDE,
    MOVE_FRUSTRATION,
    MOVE_HIDDEN_POWER,
    MOVE_MIMIC,
    MOVE_NATURAL_GIFT,
    MOVE_RAGE,
    MOVE_RETURN,
    MOVE_SECRET_POWER,
    MOVE_SUBSTITUTE,
    MOVE_TERA_BLAST,
};

//Guide Notes//
//** HM list MUST stay above TM list **//
//** Ensure no whitespace after move ids, it'll interupt py script **/
//* Use Shift + Click to highlight range to check spacing *//
//** To add to the lists in this file add the move id where you want it **//
//** And ensure itemdata is setup src/data/items.h properly for a TM or HM**//
//** pocket must be POCKET_TM_CASE, TMs have importance 0, HMs use importance 1 **//
#define TMHM_LIST
static const u16 gHM_Moves[] =
{
    MOVE_CUT,
    MOVE_FLY,
    MOVE_SURF,
    MOVE_STRENGTH,
    MOVE_FLASH,
    MOVE_ROCK_SMASH,
    MOVE_WATERFALL,
    MOVE_DIVE,
    MOVE_ROCK_CLIMB,
    LIST_END
};


static const u16 gTM_Moves[] =
{
    MOVE_FOCUS_PUNCH,
    MOVE_DRAGON_CLAW,
    MOVE_WATER_PULSE,
    MOVE_CALM_MIND,
    MOVE_ROAR,
    MOVE_TOXIC,
    MOVE_HAIL,
    MOVE_BULK_UP,
    MOVE_BULLET_SEED,
    MOVE_HIDDEN_POWER,
    MOVE_SUNNY_DAY,
    MOVE_TAUNT,
    MOVE_ICE_BEAM,
    MOVE_BLIZZARD,
    MOVE_HYPER_BEAM,
    MOVE_LIGHT_SCREEN,
    MOVE_PROTECT,
    MOVE_RAIN_DANCE,
    MOVE_GIGA_DRAIN,
    MOVE_SAFEGUARD,
    MOVE_FRUSTRATION,
    MOVE_SOLAR_BEAM,
    MOVE_IRON_TAIL,
    MOVE_THUNDERBOLT,
    MOVE_THUNDER,
    MOVE_EARTHQUAKE,
    MOVE_RETURN,
    MOVE_DIG,
    MOVE_PSYCHIC,
    MOVE_SHADOW_BALL,
    MOVE_BRICK_BREAK,
    MOVE_DOUBLE_TEAM,
    MOVE_REFLECT,
    MOVE_SHOCK_WAVE,
    MOVE_FLAMETHROWER,
    MOVE_SLUDGE_BOMB,
    MOVE_SANDSTORM,
    MOVE_FIRE_BLAST,
    MOVE_ROCK_TOMB,
    MOVE_AERIAL_ACE,
    MOVE_TORMENT,
    MOVE_FACADE,
    MOVE_SECRET_POWER,
    MOVE_REST,
    MOVE_ATTRACT,
    MOVE_THIEF,
    MOVE_STEEL_WING,
    MOVE_SKILL_SWAP,
    MOVE_SNATCH,
    MOVE_OVERHEAT,
    MOVE_WILD_CHARGE,
    MOVE_ROOST,
    MOVE_TELEPORT,
    MOVE_QUASH,
    MOVE_HONE_CLAWS,
    MOVE_BRINE,
    MOVE_CHARGE_BEAM,
    MOVE_ENDURE,
    MOVE_DRAGON_PULSE,
    MOVE_THUNDER_PUNCH,
    MOVE_FIRE_PUNCH,
    MOVE_ICE_PUNCH,
    MOVE_SHADOW_PUNCH,
    MOVE_POISON_JAB,
    MOVE_DRAIN_PUNCH,
    MOVE_COMET_PUNCH,
    MOVE_WILL_O_WISP,
    MOVE_FLASH_FREEZE,
    MOVE_MEMENTO,
    MOVE_SILVER_WIND,
    MOVE_OMINOUS_WIND,
    MOVE_FLING,
    MOVE_EMBARGO,
    MOVE_RECYCLE,
    MOVE_HEAL_BLOCK,
    MOVE_THUNDER_FANG,
    MOVE_FIRE_FANG,
    MOVE_ICE_FANG,
    MOVE_EXPLOSION,
    MOVE_SHADOW_CLAW,
    MOVE_NIGHT_SLASH,
    MOVE_RAZOR_LEAF,
    MOVE_X_SCISSOR,
    MOVE_CROSS_POISON,
    MOVE_PSYCHO_CUT,
    MOVE_FALSE_SWIPE,
    MOVE_PAYBACK,
    MOVE_GIGA_IMPACT,
    MOVE_ROCK_POLISH,
    MOVE_MUD_SPORT,
    MOVE_WATER_SPORT,
    MOVE_AURORA_VEIL,
    MOVE_STONE_EDGE,
    MOVE_REVENGE,
    MOVE_AVALANCHE,
    MOVE_THUNDER_WAVE,
    MOVE_GLARE,
    MOVE_GYRO_BALL,
    MOVE_ELECTRO_BALL,
    MOVE_SWORDS_DANCE,
    MOVE_POWER_TRICK,
    MOVE_POWER_SHIFT,
    MOVE_POWER_SWAP,
    MOVE_GUARD_SWAP,
    MOVE_SPEED_SWAP,
    MOVE_STEALTH_ROCK,
    MOVE_SPIKES,
    MOVE_FIRE_SPIN,
    MOVE_SAND_TOMB,
    MOVE_WHIRLPOOL,
    MOVE_SWARM,
    MOVE_PSYCH_UP,
    MOVE_CAPTIVATE,
    MOVE_CONFIDE,
    MOVE_FAKE_TEARS,
    MOVE_ACID_SPRAY,
    MOVE_DARK_PULSE,
    MOVE_ROCK_THROW,
    MOVE_POWER_GEM,
    MOVE_SLEEP_TALK,
    MOVE_SNORE,
    MOVE_NATURAL_GIFT,
    MOVE_GRASS_KNOT,
    MOVE_SWAGGER,
    MOVE_PLUCK,
    MOVE_BUG_BITE,
    MOVE_U_TURN,
    MOVE_VOLT_SWITCH,
    MOVE_FLIP_TURN,
    MOVE_UP_ROOT,
    MOVE_DIVE_BOMB,
    MOVE_SUBSTITUTE,
    MOVE_FLASH_CANNON,
    MOVE_AGILITY,
    MOVE_TRICK_ROOM,
    MOVE_MAGIC_ROOM,
    MOVE_WONDER_ROOM,
    MOVE_GRAVITY,
    MOVE_DRAINING_KISS,
    MOVE_LEECH_LIFE,
    MOVE_FROST_BREATH,
    MOVE_WEATHER_BALL,
    MOVE_FLAME_CHARGE,
    MOVE_TRAILBLAZE,
    MOVE_DUAL_WINGBEAT,
    MOVE_KNOCK_OFF,
    MOVE_BEAT_UP,
    MOVE_RAGE,
    MOVE_MAGIC_COAT,
    MOVE_ICICLE_SPEAR,
    MOVE_ACROBATICS,
    MOVE_ASSURANCE,
    MOVE_SOLAR_BLADE,
    MOVE_ICY_WIND,
    MOVE_METAL_CLAW,
    MOVE_HOLD_BACK,
    MOVE_HEADBUTT,
    MOVE_HI_JUMP_KICK,
    MOVE_DOUBLE_EDGE,
    MOVE_MISTY_EXPLOSION,
    MOVE_SNOWBALL,
    MOVE_ENERGY_BALL,
    MOVE_CELEBRATE,
    LIST_END
};


//ok seems pretty dumb
//but defining static globally seems to have worked...
//it compiles at least

#define NUM_TECHNICAL_MACHINES (ARRAY_COUNT(gTM_Moves) - 1) //change to 120 later  / or more plan to add on to tms I think for ease spreading certain moves
#define NUM_HIDDEN_MACHINES    (ARRAY_COUNT(gHM_Moves) - 1)

//add sound moves to list,
//round, echoed voice, hyper voice
//also smack down and think focus blast
//think give echoed voice to zubat line, as learned move or tm?
//hmm both yeah both
//need to go over scarlett violet tms and add a few 
//adding rock slide for hitmonlee 
//add gunk shot to list, poison types have WOEFULLY bad stab options *facepalm
//also venom drench  & sludge wave
//draco meteor and dragon ascent will be tutor moves
//want add other move I added as a screan to list alongside reflect and light screen
//magic coat that's it
//add heatwave
//add scorching sands
//add flash freeze  ice will o wisp and give to lunatone



/////////FILE_END///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


//
// DO NOT MODIFY BELOW THE LINE! It is auto-generated from scripts_py/tm_list.py
//


static const u16 gTMHM_List[] = {
    ITEM_HM01,
    ITEM_HM02,
    ITEM_HM03,
    ITEM_HM04,
    ITEM_HM05,
    ITEM_HM06,
    ITEM_HM07,
    ITEM_HM08,
    ITEM_HM09,
    ITEM_TM01,
    ITEM_TM02,
    ITEM_TM03,
    ITEM_TM04,
    ITEM_TM05,
    ITEM_TM06,
    ITEM_TM07,
    ITEM_TM08,
    ITEM_TM09,
    ITEM_TM10,
    ITEM_TM11,
    ITEM_TM12,
    ITEM_TM13,
    ITEM_TM14,
    ITEM_TM15,
    ITEM_TM16,
    ITEM_TM17,
    ITEM_TM18,
    ITEM_TM19,
    ITEM_TM20,
    ITEM_TM21,
    ITEM_TM22,
    ITEM_TM23,
    ITEM_TM24,
    ITEM_TM25,
    ITEM_TM26,
    ITEM_TM27,
    ITEM_TM28,
    ITEM_TM29,
    ITEM_TM30,
    ITEM_TM31,
    ITEM_TM32,
    ITEM_TM33,
    ITEM_TM34,
    ITEM_TM35,
    ITEM_TM36,
    ITEM_TM37,
    ITEM_TM38,
    ITEM_TM39,
    ITEM_TM40,
    ITEM_TM41,
    ITEM_TM42,
    ITEM_TM43,
    ITEM_TM44,
    ITEM_TM45,
    ITEM_TM46,
    ITEM_TM47,
    ITEM_TM48,
    ITEM_TM49,
    ITEM_TM50,
    ITEM_TM51,
    ITEM_TM52,
    ITEM_TM53,
    ITEM_TM54,
    ITEM_TM55,
    ITEM_TM56,
    ITEM_TM57,
    ITEM_TM58,
    ITEM_TM59,
    ITEM_TM60,
    ITEM_TM61,
    ITEM_TM62,
    ITEM_TM63,
    ITEM_TM64,
    ITEM_TM65,
    ITEM_TM66,
    ITEM_TM67,
    ITEM_TM_FLASH_FREEZE,
    ITEM_TM68,
    ITEM_TM69,
    ITEM_TM70,
    ITEM_TM71,
    ITEM_TM72,
    ITEM_TM73,
    ITEM_TM74,
    ITEM_TM75,
    ITEM_TM76,
    ITEM_TM77,
    ITEM_TM78,
    ITEM_TM79,
    ITEM_TM80,
    ITEM_TM81,
    ITEM_TM82,
    ITEM_TM83,
    ITEM_TM84,
    ITEM_TM85,
    ITEM_TM86,
    ITEM_TM87,
    ITEM_TM88,
    ITEM_TM89,
    ITEM_TM90,
    ITEM_TM91,
    ITEM_TM92,
    ITEM_TM93,
    ITEM_TM94,
    ITEM_TM95,
    ITEM_TM96,
    ITEM_TM97,
    ITEM_TM98,
    ITEM_TM99,
    ITEM_TM100,
    ITEM_TM101,
    ITEM_TM102,
    ITEM_TM103,
    ITEM_TM104,
    ITEM_TM105,
    ITEM_TM106,
    ITEM_TM107,
    ITEM_TM108,
    ITEM_TM109,
    ITEM_TM110,
    ITEM_TM111,
    ITEM_TM112,
    ITEM_TM113,
    ITEM_TM114,
    ITEM_TM115,
    ITEM_TM116,
    ITEM_TM117,
    ITEM_TM118,
    ITEM_TM119,
    ITEM_TM120,
    ITEM_TM121,
    ITEM_TM122,
    ITEM_TM123,
    ITEM_TM124,
    ITEM_TM125,
    ITEM_TM126,
    ITEM_TM127,
    ITEM_TM128,
    ITEM_TM129,
    ITEM_TM130,
    ITEM_TM131,
    ITEM_TM132,
    ITEM_TM133,
    ITEM_TM134,
    ITEM_TM135,
    ITEM_TM136,
    ITEM_TM137,
    ITEM_TM138,
    ITEM_TM139,
    ITEM_TM140,
    ITEM_TM141,
    ITEM_TM142,
    ITEM_TM_TRAILBLAZE,
    ITEM_TM143,
    ITEM_TM144,
    ITEM_TM145,
    ITEM_TM146,
    ITEM_TM147,
    ITEM_TM148,
    ITEM_TM149,
    ITEM_TM150,
    ITEM_TM151,
    ITEM_TM152,
    ITEM_TM153,
    ITEM_TM154,
    ITEM_TM155,
    ITEM_TM156,
    ITEM_TM157,
    ITEM_TM158,
    ITEM_TM159,
    ITEM_TM160,
    ITEM_TM161,
};