LavenderTown_House2_Text_WantMeToRateNicknames:: @ 8193A4B
    .string "Hello, hello!\n"
    .string "I am the official NAME RATER!\p"
    .string "Want me to rate the nicknames of\n"
    .string "your POKéMON?$"

LavenderTown_House2_Text_CritiqueWhichMonsNickname:: @ 8193AA6
    .string "Which POKéMON's nickname should\n"
    .string "I critique?$"

@change this, make multiple compare ,
@actually no just say whether its friendly enough or not
LavenderTown_House2_Text_PokemonNotUsedtoName:: @ 8193AD2
    .string "{STR_VAR_1}, is it?\n"
    .string "That is a decent nickname.\p"
    .string "But, this POKéMON doesn't seem\n"
    .string "to be used to it yet.\p"
    .string "If you grow your bond further\n"
    .string "I'll give you something quite nice!$"

LavenderTown_House2_Text_PokemonWonderfulName:: @ 8193AD2
    .string "{STR_VAR_1}, is it?\n"
    .string "That is a wonderful nickname.\p"
    .string "You can truly tell how much\n"
    .string "{STR_VAR_1} loves both you\l"
    .string "and its name!\p"
    .string "Here, please take this!$"

LavenderTown_House2_Text_DoesntHaveNickname::
    .string "Hmm, this POKéMON doesn't seem\n"
    .string "to have a nickname.\p"
    .string "Did you mean to show me\n"
    .string "someone else?$"

LavenderTown_House2_Text_WhatShallNewNicknameBe:: @ 8193B36
    .string "Ah, good. Then, what shall the new\n"
    .string "nickname be?$"

LavenderTown_House2_Text_FromNowOnShallBeKnownAsName:: @ 8193B66
    .string "Done! From now on, this POKéMON\n"
    .string "shall be known as {STR_VAR_1}!\p"
    .string "It is a better name than before!\n"
    .string "How fortunate for you!$"

LavenderTown_House2_Text_ISeeComeVisitAgain:: @ 8193BD4
    .string "I see.\n"
    .string "Do come visit again.$"

LavenderTown_House2_Text_FromNowOnShallBeKnownAsSameName:: @ 8193BF0
    .string "Done! From now on, this POKéMON\n"
    .string "shall be known as {STR_VAR_1}!\p"
    .string "It looks no different from before,\n"
    .string "and yet, this is vastly superior!\p"
    .string "How fortunate for you!$"

LavenderTown_House2_Text_TrulyImpeccableName:: @ 8193C82
    .string "{STR_VAR_1}, is it?\n"
    .string "That is a truly impeccable name!\p"
    .string "Take good care of {STR_VAR_1}!$"

LavenderTown_House2_Text_ThatIsMerelyAnEgg:: @ 8193CC4
    .string "Now, now.\n"
    .string "That is merely an EGG!$"

