Route10_PokemonCenter_1F_Text_EveryTypeStrongerThanOthers:: @ 819E523
    .string "The types of POKéMON match up\n"
    .string "differently with each other.\p"
    .string "Every type is stronger than some\n"
    .string "types and weaker than others.$"

Route10_PokemonCenter_1F_Text_NuggetUselessSoldFor5000:: @ 819E59D
    .string "A NUGGET is totally useless.\n"
    .string "So I sold it for ¥5000.$"

Route10_PokemonCenter_1F_Text_HeardGhostsHauntLavender:: @ 819E5D2
    .string "I heard that ghosts haunt\n"
    .string "LAVENDER TOWN.$"

Route10_PokemonCenter_1F_Text_GiveFloatstoneIfCaught20Mons:: @ 819E5FB
    .string "Oh… {PLAYER}!\n"
    .string "I've been looking for you!\p"
    .string "It's me, one of the ever-present\n"
    .string "AIDES to PROF. OAK.\p"
    .string "If your POKéDEX has complete data\n"
    .string "on twenty species, I'm supposed to\l"
    .string "give you a reward from PROF. OAK.\p"
    .string "He entrusted me with this\n"
    .string "FLOAT STONE.\p"
    .string "So, {PLAYER}, let me ask you.\p"
    .string "Have you gathered data on at least\n"
    .string "twenty kinds of POKéMON?$"

Route10_PokemonCenter_1F_Text_GreatHereYouGo:: @ 819E733
    .string "Great! You have caught or owned\n"
    .string "{STR_VAR_3} kinds of POKéMON!\p"
    .string "Congratulations!\n"
    .string "Here you go!$"

Route10_PokemonCenter_1F_Text_ReceivedFloatstoneFromAide:: @ 819E786
    .string "{PLAYER} received the FLOAT STONE\n"
    .string "from the AIDE.$"

@dont really want to use levitate
@but thats prob best way to get explanation accross
Route10_PokemonCenter_1F_Text_ExplainFloatstone:: @ 819E7AF
    .string "When it comes to battle being\n"
    .string "light on your feet is a good trait.\p"
    .string "That's where the FLOAT STONE comes in!\p"
    .string "It's a stupendous item that not only\n"
    .string "halves the weight of POKéMON but also\l"
    .string "makes Rock types faster!\p"
    .string "As well as make POKéMON with\n"
    .string "Flying or Wind affinity be treated\l"
    .string "as if they could levitate.$"
    
    
    @.string "Making POKéMON evolve certainly\n"
    @.string "can add to the POKéDEX.\p"
    @.string "However, at times, you may not\n"
    @.string "want a certain POKéMON to evolve.\p"
    @.string "In that case, give the EVERSTONE\n"
    @.string "to that POKéMON.\p"
    @.string "It will prevent evolution according\n"
    @.string "to the PROFESSOR.$"

